### ISSUE TITLE
Remember the default database per project

### ISSUE THREAD

**Issue by ghost** [fabianfiorotto/quick-query#25] opened 2016-06-02 18:42 UTC
**DBMS I'm using:**  MySQL (MariaDB)
**OS I'm using:**   Linux
**Theme I'm using:** One Dark
**Atom version:**  1.7.2

Hello

The active/default database feature is very useful as it removes the need to prefix queries with the database name. Would it be possible to remember the default per project/workspace instead of globally? This is most useful if you have several projects with each their own database on a local development machine.

Thanks in advance

**Comment by fabianfiorotto** [comment] 2016-06-03 13:42
That is exactly what it is doing now. How do you open a new project? Do you close the window and open a new one?

**Comment by Gert-dev** [comment] 2016-06-03 16:30
I usually use the [project-plus](https://github.com/mehcode/atom-project-plus) package to switch projects. By default, projects are opened in the same window, but you can also request them to be opened in a new window. I also sometimes have multiple windows open at the same time that are all closed and restored afterwards.

I'll try to get some more information on how exactly it's happening.

**Comment by Gert-dev** [comment] 2016-06-06 16:06
It does indeed happen via opening a new project in a new window, e.g.:
* Open project A in a new window.
* Set default database to database A.
* Close project A.
* Open project B in a new window.
* Set default database to database B.
* Close project B.
* Open project A.
* B is now the default database rather than A.

**Comment by fabianfiorotto** [comment] 2016-06-09 13:58
Did you disable `project-plus`? This problem is probably caused by a module incompatibility. You will have to disable a couple of modules and find which is causing the problem.

**Comment by Gert-dev** [comment] 2016-06-13 16:57
You are right, disabling it solves the problem. For some reason it now also doesn't occur anymore with it enabled. `project-plus` also has the option to change the active project in the active window instead of opening a new one. Would it be possible (if it doesn't happen already) to listen to `atom.project.onDidChangePaths` to also set the active database? This would automatically update the active database whenever projects change, even if they change in the same window.

**Comment by fabianfiorotto** [comment] 2017-06-01 12:16
Have you tested this again with updated versions of these packages? Anyway, they will [deprecate](https://github.com/mehcode/atom-project-plus/issues/95) `project-plus` soon so I was thinking in close this issue.

**Comment by Gert-dev** [comment] 2017-07-07 14:29
I think atom-project-manager can still open projects in the same window (via `shift+enter` by default), so this _may_ still be an issue, but only if you are currently loading state based on the active project on package activate, as I think reloading in the same window will only change project paths, but not retrigger package activation.

In any case. Do feel free to close this issue; I've also switched to atom-project-manager in the meantime and always open my projects in new windows anyway, so I don't think this will pose a problem for me anymore. Also, thanks for letting me know about the deprecation!

**Closed** 2018-10-30 17:19 UTC
